### ISSUE TITLE
Media Library / Catalog Explorer: selecting empty folder results in application error

### ISSUE THREAD

**Issue by octavian-paraschiv** [octavian-paraschiv/protone-suite#270]
Stack dump:
47	10:32:36.775	17288	OPMedia.MediaLibrary.exe	Parameter name: index
48	10:32:36.775	17288	OPMedia.MediaLibrary.exe	   at System.Windows.Forms.ListView.EnsureVisible(Int32 index)
49	10:32:36.775	17288	OPMedia.MediaLibrary.exe	   at OPMedia.Addons.Builtin.CatalogExplorer.Controls.CatalogListView.DisplayCatalogFolder(Catalog cat, CatalogItem folder, CatalogItem prevFolder)
50	10:32:36.775	17288	OPMedia.MediaLibrary.exe	   at OPMedia.Addons.Builtin.CatalogExplorer.AddonPanel.BrowseCatalogFolder(CatalogItem folder, CatalogItem prevFolder)
51	10:32:36.775	17288	OPMedia.MediaLibrary.exe	   at OPMedia.Addons.Builtin.CatalogExplorer.AddonPanel.tvCatalog_AfterSelect(Object sender, TreeViewEventArgs e)
52	10:32:36.775	17288	OPMedia.MediaLibrary.exe	   at System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
53	10:32:36.775	17288	OPMedia.MediaLibrary.exe	   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
54	10:32:36.775	17288	OPMedia.MediaLibrary.exe	   at System.Windows.Forms.TreeView.WmNotify(Message& m)
55	10:32:36.775	17288	OPMedia.MediaLibrary.exe	   at System.Windows.Forms.TreeView.WndProc(Message& m)
56	10:32:36.775	17288	OPMedia.MediaLibrary.exe	   at OPMedia.UI.Controls.OPMTreeView.WndProc(Message& m)
57	10:32:36.775	17288	OPMedia.MediaLibrary.exe	   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
58	10:32:36.775	17288	OPMedia.MediaLibrary.exe	   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
59	10:32:36.775	17288	OPMedia.MediaLibrary.exe	   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
60	10:32:37.006	17288	OPMedia.MediaLibrary.exe	TRC: Media position changed ... old=0, new=0

**Comment by octavian-paraschiv** [comment]
QA passed with build 3.0.60, needs end use confirmation
